# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://acforme.github.io
date_format: "ordinal"
title: Acforme
subtitle: "江南何采莲，莲叶何田田"
description: "Acforme的个人博客"
keywords: Acforme
favicon: /favicon.ico
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Acforme
organization: Unknown.
organization_url: Unknown
location: Beijing, China
email: Unknown

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: Acforme/Acforme.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: Acforme
douban_username: Acforme
facebook_username: Acforme
weibo_username: Acforme
zhihu_username: Acforme
twitter_username: Acforme

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: Acforme
disqus_username: Acforme
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++]
skill_mobile_app_keywords: [Android]
skill_windows_keywords: [Win32 SDK]
