# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://acforme.github.io
date_format: "ordinal"
title: Acforme
subtitle: "无语"
description: "个人博客"
keywords: acforme
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: acforme
organization:school
organization_url: 暂无
location: 暂无
email: 暂无
# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: / 暂无
    label: 首页

  -
    href: /categories/ 暂无
    label: 分类 暂无
  -
    href: /wiki/ 暂无
    label: 维基

  -
    href: /links/ 暂无
    label: 链接

  -
    href: /about/ 暂无
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections: 暂无
    wiki: 暂无
        output: true
        permalink: /wiki/:path/

repository: acforme/acforme.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: 
douban_username: 
facebook_username:
weibo_username: 
zhihu_username: 
twitter_username:

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: 
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: 
disqus_username: 
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Python, Design Patterns]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
