# ---------------- #
2	#   Main Configs   #
3	# ---------------- #
4	baseurl:
5	url: https://acforme.github.io
6	date_format: "ordinal"
7	title: 码志
8	subtitle: "打码改变人生"
9	description: "马壮的个人博客"
10	keywords: 码志, Zhuang Ma, mzlogin, mazhuang
11	favicon: /favicon.ico
12	timezone: Asia/Shanghai
13	encoding: "utf-8"
14	side_bar_repo_limit: 5
15	
16	# ---------------- #
17	#      Author      #
18	# ---------------- #
19	author: Zhuang Ma
20	organization: Sogou, Inc.
21	organization_url: https://www.sogou.com
22	location: Beijing, China
23	email: chumpma@gmail.com
24	
25	# ---------------- #
26	#    Navigation    #
27	# ---------------- #
28	navs:
29	  -
30	    href: /
31	    label: 首页
32	
33	  -
34	    href: /categories/
35	    label: 分类
36	
37	  -
38	    href: /wiki/
39	    label: 维基
40	
41	  -
42	    href: /links/
43	    label: 链接
44	
45	  -
46	    href: /about/
47	    label: 关于
48	
49	# ---------------- #
50	#       RSS        #
51	# ---------------- #
52	subscribe_rss: /feed.xml
53	
54	# ---------------- #
55	#      Jekyll      #
56	# ---------------- #
57	markdown: kramdown
58	kramdown:
59	    input: GFM
60	highlighter: rouge
61	paginate: 8
62	lsi: false
63	quiet: false
64	excerpt_separator: "\n\n"
65	permalink: /:year/:month/:day/:title/
66	gems:
67	    - jekyll-github-metadata
68	    - rouge
69	#     - jekyll-html-pipeline
70	    - jekyll-paginate
71	    - jekyll-sitemap
72	    - jekyll-feed
73	    - jemoji
74	#     - jekyll-mentions
75	collections:
76	    wiki:
77	        output: true
78	        permalink: /wiki/:path/
79	
80	repository: mzlogin/mzlogin.github.io
81	
82	# ---------------- #
83	#      Socials     #
84	# ---------------- #
85	github_username: mzlogin
86	douban_username: freedim
87	facebook_username: mzlogin
88	weibo_username: mzlogin
89	zhihu_username: mzlogin
90	twitter_username: mzlogin
91	
92	# ---------------- #
93	#      Comments    #
94	# ---------------- #
95	# support provider: disqus, duoshuo
96	comments_provider: disqus
97	# !!!重要!!! 请修改下面两个用户名为你自己申请的
98	# !!!Important!!! Please modify usernames below to yours
99	duoshuo_username: mazhuang
100	disqus_username: mzlogin
101	# 在使用 disqus 的时候可点击显示多说评论框
102	lazy_load_duoshuo: true
103	
104	# ---------------- #
105	#    Analytics     #
106	# ---------------- #
107	google:
108	    analytics_id: UA-80669434-1
109	
110	# ---------------- #
111	#      Datas       #
112	# ---------------- #
113	skill_software_keywords: [Java, C++, Python, Design Patterns]
114	skill_mobile_app_keywords: [Android, Reverse Engineering]
115	skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
